#!/usr/bin/env python3
"""
Extract the top-N words from the SymSpell frequency dictionary as a KenLM vocabulary.

Source:
    keyboard/Sources/Prediction/Resources/frequency_dictionary_en_wordfreq_50k.txt
    (generated by scripts/export_wordfreq.py from wordfreq v3.0.2)

Output format:
    One word per line (sorted by descending frequency). This is the format
    expected by KenLM's lmplz --vocab_file flag.

    The first three lines are special KenLM markers:
        <unk>  (unknown word — probability mass for OOV tokens)
        <s>    (sentence start)
        </s>   (sentence end)
    followed by the vocabulary words.

License:
    Script: Apache 2.0
    Frequency data: CC BY-SA 4.0 (original wordfreq data)
"""

import argparse
import os
import sys

# Paths relative to the repo root.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))

FREQ_DICT_PATH = os.path.join(
    REPO_ROOT,
    "keyboard/Sources/Prediction/Resources/frequency_dictionary_en_wordfreq_50k.txt",
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract KenLM vocabulary from SymSpell frequency dictionary"
    )
    parser.add_argument(
        "-n", "--top-n",
        type=int,
        default=20000,
        help="Number of words to extract (default: 20000)",
    )
    parser.add_argument(
        "-o", "--output",
        required=True,
        help="Output vocab.txt path",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite output file if it already exists",
    )
    args = parser.parse_args()

    if os.path.exists(args.output) and not args.force:
        print(
            f"Output file already exists at {args.output}",
            file=sys.stderr,
        )
        print("Pass --force to overwrite, or delete the file first.", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(FREQ_DICT_PATH):
        print(f"Frequency dictionary not found at {FREQ_DICT_PATH}", file=sys.stderr)
        sys.exit(1)

    # Read the first N words from the frequency dictionary.
    # File format: "word count" per line, sorted descending by count.
    words: list[str] = []
    with open(FREQ_DICT_PATH, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            if i >= args.top_n:
                break
            parts = line.strip().split()
            if not parts:
                continue
            word = parts[0]
            # Sanity check: word should be printable and non-empty
            if not word or any(c.isspace() for c in word):
                continue
            words.append(word)

    print(f"Read {len(words)} words from {FREQ_DICT_PATH}", file=sys.stderr)

    # Verify expected word at boundary line.
    if len(words) == args.top_n:
        print(f"Last word at position {args.top_n}: {words[-1]}", file=sys.stderr)

    # Write vocab in KenLM format: <unk>, <s>, </s> first, then words.
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("<unk>\n")
        f.write("<s>\n")
        f.write("</s>\n")
        for word in words:
            f.write(word + "\n")

    file_size_kb = os.path.getsize(args.output) / 1024
    print(f"Wrote {len(words) + 3} lines (incl. special tokens) to {args.output}")
    print(f"Output file size: {file_size_kb:.1f} KB")


if __name__ == "__main__":
    main()
